package com.ak.eventapi.dto;

import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class EventData implements java.io.Serializable {

	private Integer id;
	private Date createdDate;
	private Date downloadDate;
	private String jobSite;
	private String jobSiteId;
	private String title;
	private String link;
	private String shortText;
	private String text;
	private Integer category;
	private String budget;
	private Boolean isExecutiveSelected;
	private Boolean isForProfessional;
	private Boolean isDeleted;
	private boolean sendByEmail;
	private Integer budgetFrom;
	private Integer budgetTo;
	private String budgetCurrency;
	private Boolean budgetIsPerHour;
	private Integer budgetFromUsd;
	private Integer budgetToUsd;
	private String notes;
	private String status;
	private int rank;
	private int siteUrlId;
	private String facebookPlaceId;
	private String facebookPlaceName;
	private Date eventStartDate;
	private Date eventEndDate;
	private boolean period;

	public EventData() {
	}

	public EventData(Date createdDate, Date downloadDate, String title, boolean sendByEmail, String status, int rank,
			int siteUrlId, boolean period) {
		this.createdDate = createdDate;
		this.downloadDate = downloadDate;
		this.title = title;
		this.sendByEmail = sendByEmail;
		this.status = status;
		this.rank = rank;
		this.siteUrlId = siteUrlId;
		this.period = period;
	}

	public EventData(Date createdDate, Date downloadDate, String jobSite, String jobSiteId, String title, String link,
			String shortText, String text, Integer category, String budget, Boolean isExecutiveSelected,
			Boolean isForProfessional, Boolean isDeleted, boolean sendByEmail, Integer budgetFrom, Integer budgetTo,
			String budgetCurrency, Boolean budgetIsPerHour, Integer budgetFromUsd, Integer budgetToUsd, String notes,
			String status, int rank, int siteUrlId, String facebookPlaceId, String facebookPlaceName,
			Date eventStartDate, Date eventEndDate, boolean period) {
		this.createdDate = createdDate;
		this.downloadDate = downloadDate;
		this.jobSite = jobSite;
		this.jobSiteId = jobSiteId;
		this.title = title;
		this.link = link;
		this.shortText = shortText;
		this.text = text;
		this.category = category;
		this.budget = budget;
		this.isExecutiveSelected = isExecutiveSelected;
		this.isForProfessional = isForProfessional;
		this.isDeleted = isDeleted;
		this.sendByEmail = sendByEmail;
		this.budgetFrom = budgetFrom;
		this.budgetTo = budgetTo;
		this.budgetCurrency = budgetCurrency;
		this.budgetIsPerHour = budgetIsPerHour;
		this.budgetFromUsd = budgetFromUsd;
		this.budgetToUsd = budgetToUsd;
		this.notes = notes;
		this.status = status;
		this.rank = rank;
		this.siteUrlId = siteUrlId;
		this.facebookPlaceId = facebookPlaceId;
		this.facebookPlaceName = facebookPlaceName;
		this.eventStartDate = eventStartDate;
		this.eventEndDate = eventEndDate;
		this.period = period;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getDownloadDate() {
		return this.downloadDate;
	}

	public void setDownloadDate(Date downloadDate) {
		this.downloadDate = downloadDate;
	}

	public String getJobSite() {
		return this.jobSite;
	}

	public void setJobSite(String jobSite) {
		this.jobSite = jobSite;
	}

	public String getJobSiteId() {
		return this.jobSiteId;
	}

	public void setJobSiteId(String jobSiteId) {
		this.jobSiteId = jobSiteId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getShortText() {
		return this.shortText;
	}

	public void setShortText(String shortText) {
		this.shortText = shortText;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	public String getBudget() {
		return this.budget;
	}

	public void setBudget(String budget) {
		this.budget = budget;
	}

	public Boolean getIsExecutiveSelected() {
		return this.isExecutiveSelected;
	}

	public void setIsExecutiveSelected(Boolean isExecutiveSelected) {
		this.isExecutiveSelected = isExecutiveSelected;
	}

	public Boolean getIsForProfessional() {
		return this.isForProfessional;
	}

	public void setIsForProfessional(Boolean isForProfessional) {
		this.isForProfessional = isForProfessional;
	}

	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public boolean isSendByEmail() {
		return this.sendByEmail;
	}

	public void setSendByEmail(boolean sendByEmail) {
		this.sendByEmail = sendByEmail;
	}

	public Integer getBudgetFrom() {
		return this.budgetFrom;
	}

	public void setBudgetFrom(Integer budgetFrom) {
		this.budgetFrom = budgetFrom;
	}

	public Integer getBudgetTo() {
		return this.budgetTo;
	}

	public void setBudgetTo(Integer budgetTo) {
		this.budgetTo = budgetTo;
	}

	public String getBudgetCurrency() {
		return this.budgetCurrency;
	}

	public void setBudgetCurrency(String budgetCurrency) {
		this.budgetCurrency = budgetCurrency;
	}

	public Boolean getBudgetIsPerHour() {
		return this.budgetIsPerHour;
	}

	public void setBudgetIsPerHour(Boolean budgetIsPerHour) {
		this.budgetIsPerHour = budgetIsPerHour;
	}

	public Integer getBudgetFromUsd() {
		return this.budgetFromUsd;
	}

	public void setBudgetFromUsd(Integer budgetFromUsd) {
		this.budgetFromUsd = budgetFromUsd;
	}

	public Integer getBudgetToUsd() {
		return this.budgetToUsd;
	}

	public void setBudgetToUsd(Integer budgetToUsd) {
		this.budgetToUsd = budgetToUsd;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public int getSiteUrlId() {
		return this.siteUrlId;
	}

	public void setSiteUrlId(int siteUrlId) {
		this.siteUrlId = siteUrlId;
	}

	public String getFacebookPlaceId() {
		return this.facebookPlaceId;
	}

	public void setFacebookPlaceId(String facebookPlaceId) {
		this.facebookPlaceId = facebookPlaceId;
	}

	public String getFacebookPlaceName() {
		return this.facebookPlaceName;
	}

	public void setFacebookPlaceName(String facebookPlaceName) {
		this.facebookPlaceName = facebookPlaceName;
	}

	public Date getEventStartDate() {
		return this.eventStartDate;
	}

	public void setEventStartDate(Date eventStartDate) {
		this.eventStartDate = eventStartDate;
	}

	public Date getEventEndDate() {
		return this.eventEndDate;
	}

	public void setEventEndDate(Date eventEndDate) {
		this.eventEndDate = eventEndDate;
	}

	public boolean isPeriod() {
		return this.period;
	}

	public void setPeriod(boolean period) {
		this.period = period;
	}

}
